### GET ALL DRIVERS
GET http://localhost:8082/api/drivers

### GET PARTICULAR DRIVER
GET http://localhost:8082/api/drivers/a1234567-89ab-4cde-bf01-23456789abcd

### DELETE PARTICULAR DRIVER
DELETE http://localhost:8082/api/drivers/a1234567-89ab-4cde-bf01-23456789abcd

### CREATE
POST http://localhost:8082/api/drivers
Content-Type:  application/json

{
  "pesel": "011111111",
  "surname": "Kowal",
  "name": "Maciej",
  "age": 29
}